name: Go

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # by default only fetch one commit, then can't get diff files

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: make

      - name: "Lint"
        id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo "files: ${{ steps.files.outputs.added_modified }}"
          for file in ${{ steps.files.outputs.added_modified }}; do
            echo "lint checking ${file}."

            if [[ $file =~ \.ya?ml$ ]]; then
              output/lint schema.json "$file"
            fi

          done
